<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TroopTypeSeeder extends Seeder
{
    /**
     * @var array<int, list<array<string, mixed>>>
     */
    private const TROOP_DEFINITIONS = [
        1 => [
            [
                'code' => 'romans-legionnaire',
                'name' => 'Legionnaire',
                'attack' => 40,
                'def_inf' => 35,
                'def_cav' => 50,
                'speed' => 6,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 120,
                    'clay' => 100,
                    'iron' => 150,
                    'crop' => 30,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'romans-praetorian',
                'name' => 'Praetorian',
                'attack' => 30,
                'def_inf' => 65,
                'def_cav' => 35,
                'speed' => 5,
                'carry' => 20,
                'train_cost' => [
                    'wood' => 100,
                    'clay' => 130,
                    'iron' => 160,
                    'crop' => 70,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'romans-imperian',
                'name' => 'Imperian',
                'attack' => 70,
                'def_inf' => 40,
                'def_cav' => 25,
                'speed' => 7,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 150,
                    'clay' => 160,
                    'iron' => 210,
                    'crop' => 80,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'romans-equites-legati',
                'name' => 'Equites Legati',
                'attack' => 0,
                'def_inf' => 20,
                'def_cav' => 10,
                'speed' => 16,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 140,
                    'clay' => 160,
                    'iron' => 20,
                    'crop' => 40,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'romans-equites-imperatoris',
                'name' => 'Equites Imperatoris',
                'attack' => 120,
                'def_inf' => 65,
                'def_cav' => 50,
                'speed' => 14,
                'carry' => 100,
                'train_cost' => [
                    'wood' => 550,
                    'clay' => 440,
                    'iron' => 320,
                    'crop' => 100,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'romans-equites-caesaris',
                'name' => 'Equites Caesaris',
                'attack' => 180,
                'def_inf' => 80,
                'def_cav' => 105,
                'speed' => 10,
                'carry' => 70,
                'train_cost' => [
                    'wood' => 550,
                    'clay' => 640,
                    'iron' => 800,
                    'crop' => 180,
                ],
                'upkeep' => 4,
            ],
            [
                'code' => 'romans-battering-ram',
                'name' => 'Battering Ram',
                'attack' => 60,
                'def_inf' => 30,
                'def_cav' => 75,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 900,
                    'clay' => 360,
                    'iron' => 500,
                    'crop' => 70,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'romans-fire-catapult',
                'name' => 'Fire Catapult',
                'attack' => 75,
                'def_inf' => 60,
                'def_cav' => 10,
                'speed' => 3,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 950,
                    'clay' => 1350,
                    'iron' => 600,
                    'crop' => 90,
                ],
                'upkeep' => 6,
            ],
            [
                'code' => 'romans-senator',
                'name' => 'Senator',
                'attack' => 50,
                'def_inf' => 40,
                'def_cav' => 30,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 30750,
                    'clay' => 27200,
                    'iron' => 45000,
                    'crop' => 37500,
                ],
                'upkeep' => 5,
            ],
            [
                'code' => 'romans-settler',
                'name' => 'Settler',
                'attack' => 0,
                'def_inf' => 80,
                'def_cav' => 80,
                'speed' => 5,
                'carry' => 3000,
                'train_cost' => [
                    'wood' => 4600,
                    'clay' => 4200,
                    'iron' => 5800,
                    'crop' => 4400,
                ],
                'upkeep' => 1,
            ],
        ],
        2 => [
            [
                'code' => 'teutons-clubswinger',
                'name' => 'Clubswinger',
                'attack' => 40,
                'def_inf' => 20,
                'def_cav' => 5,
                'speed' => 7,
                'carry' => 60,
                'train_cost' => [
                    'wood' => 95,
                    'clay' => 75,
                    'iron' => 40,
                    'crop' => 40,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'teutons-spearman',
                'name' => 'Spearman',
                'attack' => 10,
                'def_inf' => 35,
                'def_cav' => 60,
                'speed' => 7,
                'carry' => 40,
                'train_cost' => [
                    'wood' => 145,
                    'clay' => 70,
                    'iron' => 85,
                    'crop' => 40,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'teutons-axeman',
                'name' => 'Axeman',
                'attack' => 60,
                'def_inf' => 30,
                'def_cav' => 30,
                'speed' => 6,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 130,
                    'clay' => 120,
                    'iron' => 170,
                    'crop' => 70,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'teutons-scout',
                'name' => 'Scout',
                'attack' => 0,
                'def_inf' => 10,
                'def_cav' => 5,
                'speed' => 9,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 160,
                    'clay' => 100,
                    'iron' => 50,
                    'crop' => 50,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'teutons-paladin',
                'name' => 'Paladin',
                'attack' => 55,
                'def_inf' => 100,
                'def_cav' => 40,
                'speed' => 10,
                'carry' => 110,
                'train_cost' => [
                    'wood' => 370,
                    'clay' => 270,
                    'iron' => 290,
                    'crop' => 75,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'teutons-teutonic-knight',
                'name' => 'Teutonic Knight',
                'attack' => 150,
                'def_inf' => 50,
                'def_cav' => 75,
                'speed' => 9,
                'carry' => 80,
                'train_cost' => [
                    'wood' => 450,
                    'clay' => 515,
                    'iron' => 480,
                    'crop' => 80,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'teutons-ram',
                'name' => 'Ram',
                'attack' => 65,
                'def_inf' => 30,
                'def_cav' => 80,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 1000,
                    'clay' => 300,
                    'iron' => 350,
                    'crop' => 70,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'teutons-catapult',
                'name' => 'Catapult',
                'attack' => 50,
                'def_inf' => 60,
                'def_cav' => 10,
                'speed' => 3,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 900,
                    'clay' => 1200,
                    'iron' => 600,
                    'crop' => 60,
                ],
                'upkeep' => 6,
            ],
            [
                'code' => 'teutons-chief',
                'name' => 'Chief',
                'attack' => 40,
                'def_inf' => 60,
                'def_cav' => 40,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 35500,
                    'clay' => 26600,
                    'iron' => 25000,
                    'crop' => 27200,
                ],
                'upkeep' => 4,
            ],
            [
                'code' => 'teutons-settler',
                'name' => 'Settler',
                'attack' => 10,
                'def_inf' => 80,
                'def_cav' => 80,
                'speed' => 5,
                'carry' => 3000,
                'train_cost' => [
                    'wood' => 5800,
                    'clay' => 4400,
                    'iron' => 4600,
                    'crop' => 5200,
                ],
                'upkeep' => 1,
            ],
        ],
        3 => [
            [
                'code' => 'gauls-phalanx',
                'name' => 'Phalanx',
                'attack' => 15,
                'def_inf' => 40,
                'def_cav' => 50,
                'speed' => 7,
                'carry' => 35,
                'train_cost' => [
                    'wood' => 100,
                    'clay' => 130,
                    'iron' => 55,
                    'crop' => 30,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'gauls-swordsman',
                'name' => 'Swordsman',
                'attack' => 65,
                'def_inf' => 35,
                'def_cav' => 20,
                'speed' => 6,
                'carry' => 45,
                'train_cost' => [
                    'wood' => 140,
                    'clay' => 150,
                    'iron' => 185,
                    'crop' => 60,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'gauls-pathfinder',
                'name' => 'Pathfinder',
                'attack' => 0,
                'def_inf' => 20,
                'def_cav' => 10,
                'speed' => 17,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 170,
                    'clay' => 150,
                    'iron' => 20,
                    'crop' => 40,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'gauls-theutates-thunder',
                'name' => 'Theutates Thunder',
                'attack' => 90,
                'def_inf' => 25,
                'def_cav' => 40,
                'speed' => 19,
                'carry' => 75,
                'train_cost' => [
                    'wood' => 350,
                    'clay' => 450,
                    'iron' => 230,
                    'crop' => 60,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'gauls-druidrider',
                'name' => 'Druidrider',
                'attack' => 45,
                'def_inf' => 115,
                'def_cav' => 55,
                'speed' => 16,
                'carry' => 35,
                'train_cost' => [
                    'wood' => 360,
                    'clay' => 330,
                    'iron' => 280,
                    'crop' => 120,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'gauls-haeduan',
                'name' => 'Haeduan',
                'attack' => 140,
                'def_inf' => 60,
                'def_cav' => 165,
                'speed' => 13,
                'carry' => 65,
                'train_cost' => [
                    'wood' => 500,
                    'clay' => 620,
                    'iron' => 675,
                    'crop' => 170,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'gauls-ram',
                'name' => 'Ram',
                'attack' => 50,
                'def_inf' => 30,
                'def_cav' => 105,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 950,
                    'clay' => 555,
                    'iron' => 330,
                    'crop' => 75,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'gauls-trebuchet',
                'name' => 'Trebuchet',
                'attack' => 70,
                'def_inf' => 45,
                'def_cav' => 10,
                'speed' => 3,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 960,
                    'clay' => 1450,
                    'iron' => 630,
                    'crop' => 90,
                ],
                'upkeep' => 6,
            ],
            [
                'code' => 'gauls-chieftain',
                'name' => 'Chieftain',
                'attack' => 40,
                'def_inf' => 50,
                'def_cav' => 50,
                'speed' => 5,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 30750,
                    'clay' => 45400,
                    'iron' => 31000,
                    'crop' => 37500,
                ],
                'upkeep' => 4,
            ],
            [
                'code' => 'gauls-settler',
                'name' => 'Settler',
                'attack' => 0,
                'def_inf' => 80,
                'def_cav' => 80,
                'speed' => 5,
                'carry' => 3000,
                'train_cost' => [
                    'wood' => 4400,
                    'clay' => 5600,
                    'iron' => 4200,
                    'crop' => 3900,
                ],
                'upkeep' => 1,
            ],
        ],
        6 => [
            [
                'code' => 'egyptians-slave-militia',
                'name' => 'Slave Militia',
                'attack' => 10,
                'def_inf' => 30,
                'def_cav' => 20,
                'speed' => 7,
                'carry' => 15,
                'train_cost' => [
                    'wood' => 45,
                    'clay' => 60,
                    'iron' => 30,
                    'crop' => 15,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'egyptians-ash-warden',
                'name' => 'Ash Warden',
                'attack' => 30,
                'def_inf' => 55,
                'def_cav' => 40,
                'speed' => 6,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 115,
                    'clay' => 100,
                    'iron' => 145,
                    'crop' => 60,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'egyptians-khopesh-warrior',
                'name' => 'Khopesh Warrior',
                'attack' => 65,
                'def_inf' => 50,
                'def_cav' => 20,
                'speed' => 7,
                'carry' => 45,
                'train_cost' => [
                    'wood' => 170,
                    'clay' => 180,
                    'iron' => 220,
                    'crop' => 80,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'egyptians-sopdu-explorer',
                'name' => 'Sopdu Explorer',
                'attack' => 0,
                'def_inf' => 20,
                'def_cav' => 10,
                'speed' => 16,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 170,
                    'clay' => 150,
                    'iron' => 20,
                    'crop' => 40,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'egyptians-anhur-guard',
                'name' => 'Anhur Guard',
                'attack' => 50,
                'def_inf' => 110,
                'def_cav' => 50,
                'speed' => 15,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 360,
                    'clay' => 330,
                    'iron' => 280,
                    'crop' => 120,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'egyptians-resheph-chariot',
                'name' => 'Resheph Chariot',
                'attack' => 110,
                'def_inf' => 120,
                'def_cav' => 150,
                'speed' => 10,
                'carry' => 70,
                'train_cost' => [
                    'wood' => 450,
                    'clay' => 560,
                    'iron' => 610,
                    'crop' => 180,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'egyptians-ram',
                'name' => 'Ram',
                'attack' => 55,
                'def_inf' => 30,
                'def_cav' => 95,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 995,
                    'clay' => 575,
                    'iron' => 340,
                    'crop' => 80,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'egyptians-stone-catapult',
                'name' => 'Stone Catapult',
                'attack' => 65,
                'def_inf' => 55,
                'def_cav' => 10,
                'speed' => 3,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 980,
                    'clay' => 1510,
                    'iron' => 660,
                    'crop' => 100,
                ],
                'upkeep' => 6,
            ],
            [
                'code' => 'egyptians-nomarch',
                'name' => 'Nomarch',
                'attack' => 40,
                'def_inf' => 50,
                'def_cav' => 50,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 34000,
                    'clay' => 50000,
                    'iron' => 34000,
                    'crop' => 42000,
                ],
                'upkeep' => 4,
            ],
            [
                'code' => 'egyptians-settler',
                'name' => 'Settler',
                'attack' => 0,
                'def_inf' => 80,
                'def_cav' => 80,
                'speed' => 5,
                'carry' => 3000,
                'train_cost' => [
                    'wood' => 4560,
                    'clay' => 5890,
                    'iron' => 4370,
                    'crop' => 4180,
                ],
                'upkeep' => 1,
            ],
        ],
        7 => [
            [
                'code' => 'huns-mercenary',
                'name' => 'Mercenary',
                'attack' => 35,
                'def_inf' => 40,
                'def_cav' => 30,
                'speed' => 6,
                'carry' => 50,
                'train_cost' => [
                    'wood' => 130,
                    'clay' => 80,
                    'iron' => 40,
                    'crop' => 40,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'huns-bowman',
                'name' => 'Bowman',
                'attack' => 50,
                'def_inf' => 30,
                'def_cav' => 10,
                'speed' => 6,
                'carry' => 30,
                'train_cost' => [
                    'wood' => 140,
                    'clay' => 110,
                    'iron' => 60,
                    'crop' => 60,
                ],
                'upkeep' => 1,
            ],
            [
                'code' => 'huns-spotter',
                'name' => 'Spotter',
                'attack' => 0,
                'def_inf' => 20,
                'def_cav' => 10,
                'speed' => 19,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 170,
                    'clay' => 150,
                    'iron' => 20,
                    'crop' => 40,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'huns-steppe-rider',
                'name' => 'Steppe Rider',
                'attack' => 120,
                'def_inf' => 30,
                'def_cav' => 15,
                'speed' => 16,
                'carry' => 115,
                'train_cost' => [
                    'wood' => 290,
                    'clay' => 370,
                    'iron' => 190,
                    'crop' => 45,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'huns-marksman',
                'name' => 'Marksman',
                'attack' => 115,
                'def_inf' => 80,
                'def_cav' => 70,
                'speed' => 16,
                'carry' => 105,
                'train_cost' => [
                    'wood' => 320,
                    'clay' => 350,
                    'iron' => 330,
                    'crop' => 50,
                ],
                'upkeep' => 2,
            ],
            [
                'code' => 'huns-marauder',
                'name' => 'Marauder',
                'attack' => 180,
                'def_inf' => 60,
                'def_cav' => 40,
                'speed' => 14,
                'carry' => 80,
                'train_cost' => [
                    'wood' => 450,
                    'clay' => 560,
                    'iron' => 610,
                    'crop' => 140,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'huns-ram',
                'name' => 'Ram',
                'attack' => 65,
                'def_inf' => 30,
                'def_cav' => 90,
                'speed' => 4,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 1060,
                    'clay' => 330,
                    'iron' => 360,
                    'crop' => 70,
                ],
                'upkeep' => 3,
            ],
            [
                'code' => 'huns-catapult',
                'name' => 'Catapult',
                'attack' => 45,
                'def_inf' => 55,
                'def_cav' => 10,
                'speed' => 3,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 950,
                    'clay' => 1280,
                    'iron' => 620,
                    'crop' => 60,
                ],
                'upkeep' => 6,
            ],
            [
                'code' => 'huns-logades',
                'name' => 'Logades',
                'attack' => 40,
                'def_inf' => 50,
                'def_cav' => 50,
                'speed' => 5,
                'carry' => 0,
                'train_cost' => [
                    'wood' => 37200,
                    'clay' => 27600,
                    'iron' => 25200,
                    'crop' => 27600,
                ],
                'upkeep' => 4,
            ],
            [
                'code' => 'huns-settler',
                'name' => 'Settler',
                'attack' => 0,
                'def_inf' => 80,
                'def_cav' => 80,
                'speed' => 5,
                'carry' => 3000,
                'train_cost' => [
                    'wood' => 6100,
                    'clay' => 4600,
                    'iron' => 4800,
                    'crop' => 5400,
                ],
                'upkeep' => 1,
            ],
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = Carbon::now();

        $rows = [];

        foreach (self::TROOP_DEFINITIONS as $tribe => $units) {
            foreach ($units as $unit) {
                $rows[] = [
                    'tribe' => $tribe,
                    'code' => $unit['code'],
                    'name' => $unit['name'],
                    'attack' => $unit['attack'],
                    'def_inf' => $unit['def_inf'],
                    'def_cav' => $unit['def_cav'],
                    'speed' => $unit['speed'],
                    'carry' => $unit['carry'],
                    'train_cost' => json_encode($unit['train_cost'], JSON_THROW_ON_ERROR),
                    'upkeep' => $unit['upkeep'],
                    'created_at' => $timestamp,
                    'updated_at' => $timestamp,
                ];
            }
        }

        DB::table('troop_types')->upsert(
            $rows,
            ['tribe', 'code'],
            ['name', 'attack', 'def_inf', 'def_cav', 'speed', 'carry', 'train_cost', 'upkeep', 'updated_at'],
        );
    }
}
