<?php

return [
    'buildings' => [
        [
            'code' => 'woodcutter',
            'name' => 'Woodcutter',
            'category' => 'resource',
            'max_level' => 20,
            'is_resource_field' => true,
            'base_cost' => [
                'wood' => 40,
                'clay' => 100,
                'iron' => 50,
                'crop' => 60,
                'build_time' => 5,
            ],
            'production' => [
                'resource' => 'wood',
                'base' => 7,
                'factor' => 1.6,
            ],
            'bonuses' => null,
        ],
        [
            'code' => 'clay_pit',
            'name' => 'Clay Pit',
            'category' => 'resource',
            'max_level' => 20,
            'is_resource_field' => true,
            'base_cost' => [
                'wood' => 80,
                'clay' => 40,
                'iron' => 80,
                'crop' => 50,
                'build_time' => 5,
            ],
            'production' => [
                'resource' => 'clay',
                'base' => 7,
                'factor' => 1.6,
            ],
            'bonuses' => null,
        ],
        [
            'code' => 'iron_mine',
            'name' => 'Iron Mine',
            'category' => 'resource',
            'max_level' => 20,
            'is_resource_field' => true,
            'base_cost' => [
                'wood' => 100,
                'clay' => 80,
                'iron' => 30,
                'crop' => 60,
                'build_time' => 5,
            ],
            'production' => [
                'resource' => 'iron',
                'base' => 6,
                'factor' => 1.6,
            ],
            'bonuses' => null,
        ],
        [
            'code' => 'cropland',
            'name' => 'Cropland',
            'category' => 'resource',
            'max_level' => 20,
            'is_resource_field' => true,
            'base_cost' => [
                'wood' => 70,
                'clay' => 90,
                'iron' => 70,
                'crop' => 20,
                'build_time' => 5,
            ],
            'production' => [
                'resource' => 'crop',
                'base' => 6,
                'factor' => 1.5,
            ],
            'bonuses' => null,
        ],
        [
            'code' => 'main_building',
            'name' => 'Main Building',
            'category' => 'infrastructure',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 70,
                'clay' => 40,
                'iron' => 60,
                'crop' => 20,
                'build_time' => 7,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'build_speed',
                'modifier_per_level' => 0.05,
            ],
        ],
        [
            'code' => 'warehouse',
            'name' => 'Warehouse',
            'category' => 'storage',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 130,
                'clay' => 160,
                'iron' => 90,
                'crop' => 40,
                'build_time' => 8,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'storage',
                'resource' => 'warehouse',
                'base_capacity' => 800,
            ],
        ],
        [
            'code' => 'granary',
            'name' => 'Granary',
            'category' => 'storage',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 80,
                'clay' => 100,
                'iron' => 70,
                'crop' => 20,
                'build_time' => 8,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'storage',
                'resource' => 'granary',
                'base_capacity' => 800,
            ],
        ],
        [
            'code' => 'barracks',
            'name' => 'Barracks',
            'category' => 'military',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 210,
                'clay' => 140,
                'iron' => 260,
                'crop' => 120,
                'build_time' => 12,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'training_speed',
                'unit_scope' => 'infantry',
                'modifier_per_level' => 0.04,
            ],
        ],
        [
            'code' => 'stable',
            'name' => 'Stable',
            'category' => 'military',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 260,
                'clay' => 140,
                'iron' => 220,
                'crop' => 100,
                'build_time' => 16,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'training_speed',
                'unit_scope' => 'cavalry',
                'modifier_per_level' => 0.04,
            ],
        ],
        [
            'code' => 'rally_point',
            'name' => 'Rally Point',
            'category' => 'military',
            'max_level' => 20,
            'is_resource_field' => false,
            'base_cost' => [
                'wood' => 110,
                'clay' => 160,
                'iron' => 90,
                'crop' => 70,
                'build_time' => 6,
            ],
            'production' => null,
            'bonuses' => [
                'type' => 'movement_control',
            ],
        ],
    ],

    'troops' => [
        [
            'code' => 'roman_legionnaire',
            'name' => 'Legionnaire',
            'tribe' => 'romans',
            'training_building' => 'barracks',
            'attack' => 40,
            'defense_infantry' => 35,
            'defense_cavalry' => 50,
            'speed' => 6,
            'carry' => 50,
            'crop' => 1,
            'cost' => [
                'wood' => 120,
                'clay' => 100,
                'iron' => 150,
                'crop' => 30,
                'training_time' => 80,
            ],
        ],
        [
            'code' => 'roman_praetorian',
            'name' => 'Praetorian',
            'tribe' => 'romans',
            'training_building' => 'barracks',
            'attack' => 30,
            'defense_infantry' => 65,
            'defense_cavalry' => 35,
            'speed' => 5,
            'carry' => 20,
            'crop' => 1,
            'cost' => [
                'wood' => 100,
                'clay' => 130,
                'iron' => 160,
                'crop' => 70,
                'training_time' => 100,
            ],
        ],
        [
            'code' => 'roman_imperian',
            'name' => 'Imperian',
            'tribe' => 'romans',
            'training_building' => 'barracks',
            'attack' => 70,
            'defense_infantry' => 40,
            'defense_cavalry' => 25,
            'speed' => 7,
            'carry' => 50,
            'crop' => 1,
            'cost' => [
                'wood' => 150,
                'clay' => 160,
                'iron' => 210,
                'crop' => 80,
                'training_time' => 120,
            ],
        ],
        [
            'code' => 'gaul_phalanx',
            'name' => 'Phalanx',
            'tribe' => 'gauls',
            'training_building' => 'barracks',
            'attack' => 15,
            'defense_infantry' => 40,
            'defense_cavalry' => 50,
            'speed' => 7,
            'carry' => 35,
            'crop' => 1,
            'cost' => [
                'wood' => 100,
                'clay' => 130,
                'iron' => 55,
                'crop' => 30,
                'training_time' => 80,
            ],
        ],
        [
            'code' => 'teuton_clubman',
            'name' => 'Clubman',
            'tribe' => 'teutons',
            'training_building' => 'barracks',
            'attack' => 40,
            'defense_infantry' => 20,
            'defense_cavalry' => 5,
            'speed' => 7,
            'carry' => 60,
            'crop' => 1,
            'cost' => [
                'wood' => 95,
                'clay' => 75,
                'iron' => 40,
                'crop' => 40,
                'training_time' => 80,
            ],
        ],
    ],

    'quests' => [
        [
            'code' => 'tutorial_welcome',
            'category' => 'tutorial',
            'title' => 'Welcome to the village',
            'description' => 'Build your first Woodcutter to start producing lumber.',
            'requirements' => [
                'type' => 'building_level',
                'building' => 'woodcutter',
                'level' => 1,
            ],
            'rewards' => [
                'resources' => [
                    'wood' => 50,
                    'clay' => 50,
                    'iron' => 30,
                    'crop' => 30,
                ],
                'culture_points' => 1,
            ],
            'repeatable' => false,
        ],
        [
            'code' => 'tutorial_train_unit',
            'category' => 'tutorial',
            'title' => 'Train your first troop',
            'description' => 'Queue at least one infantry unit in the barracks.',
            'requirements' => [
                'type' => 'train_units',
                'building' => 'barracks',
                'amount' => 1,
            ],
            'rewards' => [
                'resources' => [
                    'wood' => 80,
                    'clay' => 50,
                    'iron' => 60,
                    'crop' => 40,
                ],
                'hero_experience' => 20,
            ],
            'repeatable' => false,
        ],
        [
            'code' => 'daily_resource_turnin',
            'category' => 'daily',
            'title' => 'Contribute resources',
            'description' => 'Send 1,000 resources via trade routes or marketplace.',
            'requirements' => [
                'type' => 'contribute_resources',
                'amount' => 1000,
            ],
            'rewards' => [
                'silver' => 50,
            ],
            'repeatable' => true,
        ],
    ],
];
