<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
CREATE TABLE IF NOT EXISTS `users`
(
  `id`                                               INT(11) UNSIGNED      NOT NULL AUTO_INCREMENT,
  `uuid`                                             VARCHAR(40)           NULL,
  `aid`                                              INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `alliance_role_name`                               VARCHAR(20)           NOT NULL DEFAULT '',
  `alliance_role`                                    MEDIUMINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `alliance_join_time`                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `alliance_contributions`                           BIGINT(11) UNSIGNED   NOT NULL DEFAULT '0',
  `name`                                             VARCHAR(20)           NOT NULL,
  `password`                                         VARCHAR(40)           NOT NULL,
  `email`                                            VARCHAR(99)           NULL     DEFAULT '',
  `email_verified`                                   TINYINT(3) UNSIGNED   NOT NULL DEFAULT '0',
  `race`                                             TINYINT(1) UNSIGNED   NOT NULL,
  `access`                                           TINYINT(1) UNSIGNED   NOT NULL DEFAULT '1',
  `countryFlag`                                      VARCHAR(30)           NULL,
  `showMedals`                                       TINYINT(1)            NULL     DEFAULT '0',
  `showCountryFlag`                                  TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `lastCountryFlagCheck`                             INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `kid`                                              INT(6) UNSIGNED       NOT NULL,
  `total_name_changes`                               TINYINT(3)            NOT NULL DEFAULT '0',
  `total_pop`                                        BIGINT(255)           NOT NULL DEFAULT '0',
  `total_villages`                                   INT(5)                NOT NULL DEFAULT '0',
  `favorTabs`                                        VARCHAR(40)           NOT NULL DEFAULT '0,0,0,1,0,0,0,0,1,0,0,0,0,0',
  `reportFilters`                                    VARCHAR(20)           NOT NULL DEFAULT '0,0,0,7,31,31,127',
  `allianceSettings`                                 VARCHAR(10)           NOT NULL DEFAULT '0|0|0|0|0',
  `allianceNotificationEnabled`                      TINYINT(1)            NOT NULL DEFAULT '1',
  `autoComplete`                                     VARCHAR(5)            NOT NULL DEFAULT '1,0,0',
  `display`                                          VARCHAR(20)           NOT NULL DEFAULT '0,10,10,0,0,0',
  `timezone`                                         VARCHAR(5)            NOT NULL DEFAULT '0,0',
  `mapMarkSettings`                                  VARCHAR(3)            NOT NULL DEFAULT '1,0',
  `qst_tut`                                          VARCHAR(10)           NOT NULL DEFAULT '1-0',
  `qst_economy`                                      VARCHAR(50)           NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0',
  `qst_world`                                        VARCHAR(50)           NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
  `qst_battle`                                       VARCHAR(50)           NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
  `gift_gold`                                        INT(11)               NOT NULL DEFAULT '0',
  `bought_gold`                                      INT(11)               NOT NULL DEFAULT '0',
  `silver`                                           INT(11)               NOT NULL DEFAULT '0',
  `plus`                                             INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `b1`                                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `b2`                                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `b3`                                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `b4`                                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `atkBonusExpireTime`                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `defBonusExpireTime`                               INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `lastBuyResources`                                 INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `lastBuyAnimals`                                   INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `lastBuyTroops`                                    INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `fasterTraining`                                   INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `gender`                                           TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `birthday`                                         VARCHAR(50)           NOT NULL DEFAULT '0',
  `location`                                         VARCHAR(30)           NOT NULL DEFAULT '0',
  `language`                                         VARCHAR(30)           NOT NULL DEFAULT '0',
  `desc1`                                            LONGTEXT              NOT NULL,
  `desc2`                                            LONGTEXT              NOT NULL,
  `note`                                             LONGTEXT              NOT NULL,
  `sit1Uid`                                          INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `sit1Permissions`                                  SMALLINT(3) UNSIGNED  NOT NULL DEFAULT '87',
  `sit2Uid`                                          INT(11) UNSIGNED      NOT NULL DEFAULT '0',
  `sit2Permissions`                                  SMALLINT(3) UNSIGNED  NOT NULL DEFAULT '87',
  `goldclub`                                         TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `escape`                                           TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `total_attack_points`                              BIGINT(255) UNSIGNED  NOT NULL DEFAULT '0',
  `total_defense_points`                             BIGINT(255) UNSIGNED  NOT NULL DEFAULT '0',
  `week_attack_points`                               BIGINT(255) UNSIGNED  NOT NULL DEFAULT '0',
  `week_defense_points`                              BIGINT(255) UNSIGNED  NOT NULL DEFAULT '0',
  `week_robber_points`                               BIGINT(255)           NOT NULL DEFAULT '0',
  `week_alliance_training_contributions`             BIGINT(255)           NOT NULL DEFAULT '0',
  `week_alliance_armor_contributions`                BIGINT(255)           NOT NULL DEFAULT '0',
  `week_alliance_cp_contributions`                   BIGINT(255)           NOT NULL DEFAULT '0',
  `week_alliance_trade_contributions`                BIGINT(255)           NOT NULL DEFAULT '0',
  `total_alliance_training_contributions`            BIGINT(255)           NOT NULL DEFAULT '0',
  `total_alliance_armor_contributions`               BIGINT(255)           NOT NULL DEFAULT '0',
  `total_alliance_cp_contributions`                  BIGINT(255)           NOT NULL DEFAULT '0',
  `total_alliance_trade_contributions`               BIGINT(255)           NOT NULL DEFAULT '0',
  `pending_training_alliance_bonus_unlock_animation` TINYINT(1)            NOT NULL DEFAULT '0',
  `pending_armor_alliance_bonus_unlock_animation`    TINYINT(1)            NOT NULL DEFAULT '0',
  `pending_cp_alliance_bonus_unlock_animation`       TINYINT(1)            NOT NULL DEFAULT '0',
  `pending_trade_alliance_bonus_unlock_animation`    TINYINT(1)            NOT NULL DEFAULT '0',
  `max_off_point`                                    BIGINT(255)           NOT NULL DEFAULT '0',
  `max_off_time`                                     INT(11)               NOT NULL DEFAULT '0',
  `max_off_nid`                                      INT(11)               NOT NULL DEFAULT '0',
  `max_def_point`                                    BIGINT(255)           NOT NULL DEFAULT '0',
  `max_def_time`                                     INT(11)               NOT NULL DEFAULT '0',
  `max_def_nid`                                      INT(11)               NOT NULL DEFAULT '0',
  `oldRank`                                          INT(11)               NOT NULL DEFAULT '-1',
  `cp`                                               INT(11) UNSIGNED      NOT NULL DEFAULT '1',
  `cp_prod`                                          INT(11)               NOT NULL DEFAULT '0',
  `ok`                                               TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `lastupdate`                                       INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `lastPkgCodeTry`                                   INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `pkgCodeTries`                                     INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `last_adventure_time`                              INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `total_adventures`                                 INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `success_adventures_count`                         INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `success_adventures_hex`                           INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `lastVillageExpand`                                INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `lastHeroExpCheck`                                 INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `signupTime`                                       INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `protection`                                       INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `protectionLastExtend`                             INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `protectionBoughtHours`                            INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `last_login_time`                                  INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `last_owner_login_time`                            INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `lastMultiAccountCheck`                            INT(11) UNSIGNED      NOT NULL DEFAULT '1',
  `vacationActiveTil`                                INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `profileCacheVersion`                              INT(10) UNSIGNED      NOT NULL DEFAULT '0',
  `vacationUsedDays`                                 INT(5) UNSIGNED       NOT NULL DEFAULT '0',
  `hidden`                                           TINYINT(1) UNSIGNED   NOT NULL DEFAULT '0',
  `ajax_token`                                       VARCHAR(50)           NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `findPlayer` (`name`, `email`),
  KEY `sitters` (`sit1Uid`, `sit2Uid`),
  KEY `productionBoostAndPlus` (`plus`, `b1`, `b2`, `b3`, `b4`),
  KEY `update_search` (`lastVillageExpand`, `lastMultiAccountCheck`, `lastCountryFlagCheck`, `last_adventure_time`,
                       `lastupdate`, `last_login_time`),
  KEY `statistics` (`countryFlag`, `total_attack_points`, `total_defense_points`, `week_attack_points`,
                    `week_defense_points`, `week_robber_points`, `oldRank`, `total_pop`, `total_villages`,
                    `max_off_point`, `max_def_point`, `hidden`),
  UNIQUE KEY (`uuid`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
SQL
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
