name: Auto merge labeled pull requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - labeled
      - unlabeled

jobs:
  enable-auto-merge:
    if: >
      github.event.action != 'unlabeled' &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.draft == false &&
      contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable GitHub auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge

  disable-auto-merge:
    if: >
      github.event.action == 'unlabeled' &&
      github.event.label.name == 'automerge' &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Disable GitHub auto-merge
        uses: peter-evans/disable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
